name: Deploy Infrastructure and Configure Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Generate Ansible Inventory
        run: python3 scripts/generate_inventory.py

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory/hosts ansible/playbooks/configure_servers.yml
